//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genius_Business.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class etddatabaseEntities1 : DbContext
    {
        public etddatabaseEntities1()
            : base("name=etddatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Codigos> Codigos { get; set; }
        public virtual DbSet<GbB_cliente> GbB_cliente { get; set; }
        public virtual DbSet<GbB_ventas> GbB_ventas { get; set; }
        public virtual DbSet<GbB_ventasreales> GbB_ventasreales { get; set; }
        public virtual DbSet<GnB_Empresas> GnB_Empresas { get; set; }
        public virtual DbSet<GnB_EmpresasLicencias> GnB_EmpresasLicencias { get; set; }
        public virtual DbSet<Licencias> Licencias { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<GbB_Tiendas> GbB_Tiendas { get; set; }
        public virtual DbSet<GbB_productos> GbB_productos { get; set; }
        public virtual DbSet<GbB_materiales> GbB_materiales { get; set; }
    }
}
