//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genius_Business.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GbB_cliente
    {
        public long cliente_idempresa { get; set; }
        public long cleinte_id { get; set; }
        public System.DateTime venta_fecha { get; set; }
        public string venta_nombre { get; set; }
        public string venta_apellidos { get; set; }
        public string venta_telefono { get; set; }
        public string venta_email { get; set; }
        public string venta_redessociale { get; set; }
    }
}
