//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genius_Business.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GbB_materiales
    {
        public long material_idempresa { get; set; }
        public long material_id { get; set; }
        public System.DateTime material_fecha { get; set; }
        public Nullable<long> material_tiendaid { get; set; }
        public Nullable<decimal> material_costeunidad { get; set; }
        public byte[] material_imagen { get; set; }
        public Nullable<decimal> material_stock { get; set; }
        public string material_nombre { get; set; }
        public string material_unidad { get; set; }
        public Nullable<decimal> material_costefabricación { get; set; }
    }
}
