//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genius_Business.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GbB_Tiendas
    {
        public long tienda_idempresa { get; set; }
        public long tienda_id { get; set; }
        public string tienda_NombreTienda { get; set; }
        public string tienda_Direccion { get; set; }
        public string tienda_Población { get; set; }
        public Nullable<int> tienda_Pais { get; set; }
    }
}
