//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genius_Business.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GbB_productos
    {
        public long producto_idempresa { get; set; }
        public long producto_id { get; set; }
        public System.DateTime producto_fecha { get; set; }
        public Nullable<long> producto_tiendaid { get; set; }
        public Nullable<decimal> producto_costeunidad { get; set; }
        public decimal producto_preciounidad { get; set; }
        public decimal producto_ivaporcent { get; set; }
        public byte[] producto_imagen { get; set; }
        public Nullable<decimal> producto_stock { get; set; }
        public string producto_nombre { get; set; }
        public string producto_unidad { get; set; }
        public Nullable<decimal> producto_costefabricación { get; set; }
        public string producto_codigoproducto { get; set; }
    }
}
