//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genius_Business.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GbB_ventasreales
    {
        public long ventareal_idempresa { get; set; }
        public long ventareal_ventas_id { get; set; }
        public Nullable<long> ventareal_idproducto { get; set; }
        public Nullable<int> ventareal_cantidad { get; set; }
        public Nullable<decimal> ventareal_costeunidad { get; set; }
        public Nullable<decimal> ventarela_costetotal { get; set; }
        public Nullable<decimal> ventareal_preciounidad { get; set; }
        public Nullable<decimal> ventareal_descuentounidad { get; set; }
        public Nullable<decimal> ventareal_total { get; set; }
        public Nullable<decimal> ventareal_ivaporcent { get; set; }
        public Nullable<decimal> ventareal_ivaTotal { get; set; }
        public Nullable<decimal> vantareal_totaliva { get; set; }
        public System.DateTime ventareal_fecha { get; set; }
    }
}
