//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genius_Business.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GnB_Empresas
    {
        public long Empresa_idEmpresa { get; set; }
        public string Nombre_Empresa { get; set; }
        public string Emailprincipal { get; set; }
        public string NumTel { get; set; }
        public string ContraseñaEmpresa { get; set; }
        public string Pais { get; set; }
        public Nullable<int> cuentastrial { get; set; }
    }
}
