//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genius_Business.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GnB_EmpresasLicencias
    {
        public long Emlc_idlicencia { get; set; }
        public long Emlc_idEmpresa { get; set; }
        public string Nombre_Empresa { get; set; }
        public string Nombre_Pais { get; set; }
    }
}
