//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genius_Business.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licencias
    {
        public string id_App { get; set; }
        public string email { get; set; }
        public string program_key { get; set; }
        public string mac { get; set; }
        public Nullable<System.DateTime> limitdate { get; set; }
        public string version { get; set; }
        public long id { get; set; }
        public Nullable<bool> testing { get; set; }
    }
}
