//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genius_Business.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paises
    {
        public long paises_id { get; set; }
        public string paises_pais { get; set; }
        public string paises_moneda { get; set; }
    }
}
