//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genius_Business.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Multilanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Multilanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genius_Business.Resources.Multilanguage", typeof(Multilanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar.
        /// </summary>
        public static string Activar {
            get {
                return ResourceManager.GetString("Activar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir.
        /// </summary>
        public static string Añadir {
            get {
                return ResourceManager.GetString("Añadir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Material.
        /// </summary>
        public static string AñadirMaterial {
            get {
                return ResourceManager.GetString("AñadirMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir  producto.
        /// </summary>
        public static string Añadirproducto {
            get {
                return ResourceManager.GetString("Añadirproducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Tienda.
        /// </summary>
        public static string AñadirTienda {
            get {
                return ResourceManager.GetString("AñadirTienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        public static string Año {
            get {
                return ResourceManager.GetString("Año", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociar Empresa.
        /// </summary>
        public static string AsociarEmpresa {
            get {
                return ResourceManager.GetString("AsociarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogo de Materiales.
        /// </summary>
        public static string Catálogomateriales {
            get {
                return ResourceManager.GetString("Catálogomateriales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalógo de productos.
        /// </summary>
        public static string CatalogoProductos {
            get {
                return ResourceManager.GetString("CatalogoProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave producto:.
        /// </summary>
        public static string ClaveProducto {
            get {
                return ResourceManager.GetString("ClaveProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código  Producto.
        /// </summary>
        public static string CódigoProducto {
            get {
                return ResourceManager.GetString("CódigoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprar Licencia.
        /// </summary>
        public static string ComprarLicencia {
            get {
                return ResourceManager.GetString("ComprarLicencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string Configuración {
            get {
                return ResourceManager.GetString("Configuración", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña:.
        /// </summary>
        public static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conraseña de la empresa.
        /// </summary>
        public static string ContraseñaEmpresa {
            get {
                return ResourceManager.GetString("ContraseñaEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coste fabricación.
        /// </summary>
        public static string CosteFabricación {
            get {
                return ResourceManager.GetString("CosteFabricación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coste Material por Unidad.
        /// </summary>
        public static string CosteMaterialporunidad {
            get {
                return ResourceManager.GetString("CosteMaterialporunidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coste por unidad.
        /// </summary>
        public static string Costeproducto {
            get {
                return ResourceManager.GetString("Costeproducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Material.
        /// </summary>
        public static string Editar_Material {
            get {
                return ResourceManager.GetString("Editar Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Producto.
        /// </summary>
        public static string EditarProducto {
            get {
                return ResourceManager.GetString("EditarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Producto.
        /// </summary>
        public static string Eliminar_Producto {
            get {
                return ResourceManager.GetString("Eliminar Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Material.
        /// </summary>
        public static string EliminarMaterial {
            get {
                return ResourceManager.GetString("EliminarMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electronico:.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email principal de la empresa:.
        /// </summary>
        public static string Emailprincipal {
            get {
                return ResourceManager.GetString("Emailprincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empecemos.
        /// </summary>
        public static string Empecemos {
            get {
                return ResourceManager.GetString("Empecemos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examinar.
        /// </summary>
        public static string Examinar {
            get {
                return ResourceManager.GetString("Examinar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finanzas.
        /// </summary>
        public static string Finanzas {
            get {
                return ResourceManager.GetString("Finanzas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haga el login de su compañia.
        /// </summary>
        public static string Hagalogin {
            get {
                return ResourceManager.GetString("Hagalogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen.
        /// </summary>
        public static string Imagen {
            get {
                return ResourceManager.GetString("Imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string IniciarSesion {
            get {
                return ResourceManager.GetString("IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca datos de su compañia.
        /// </summary>
        public static string Introduzcadatoscompañia {
            get {
                return ResourceManager.GetString("Introduzcadatoscompañia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materiales.
        /// </summary>
        public static string Materiales {
            get {
                return ResourceManager.GetString("Materiales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensajes.
        /// </summary>
        public static string Mensajes {
            get {
                return ResourceManager.GetString("Mensajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes.
        /// </summary>
        public static string Mes {
            get {
                return ResourceManager.GetString("Mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        public static string Moneda {
            get {
                return ResourceManager.GetString("Moneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necesita validar su licencia.
        /// </summary>
        public static string NecesitaValidar {
            get {
                return ResourceManager.GetString("NecesitaValidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la Empresa.
        /// </summary>
        public static string NombreEmpresa {
            get {
                return ResourceManager.GetString("NombreEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Material.
        /// </summary>
        public static string NombreMaterial {
            get {
                return ResourceManager.GetString("NombreMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del producto.
        /// </summary>
        public static string Nombreproducto {
            get {
                return ResourceManager.GetString("Nombreproducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Tienda.
        /// </summary>
        public static string NombreTienda {
            get {
                return ResourceManager.GetString("NombreTienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número telefono.
        /// </summary>
        public static string NumTel {
            get {
                return ResourceManager.GetString("NumTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otros.
        /// </summary>
        public static string Otros {
            get {
                return ResourceManager.GetString("Otros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País:.
        /// </summary>
        public static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string País {
            get {
                return ResourceManager.GetString("País", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plazo.
        /// </summary>
        public static string Plazo {
            get {
                return ResourceManager.GetString("Plazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Población.
        /// </summary>
        public static string Población {
            get {
                return ResourceManager.GetString("Población", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % IVA.
        /// </summary>
        public static string Porcentaje_iva {
            get {
                return ResourceManager.GetString("Porcentaje iva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio sin IVA.
        /// </summary>
        public static string Precio_unidad {
            get {
                return ResourceManager.GetString("Precio unidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La empresa ya esta registrada en la plataforma o es  una nueva?.
        /// </summary>
        public static string pregunta1 {
            get {
                return ResourceManager.GetString("pregunta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probar 3 dias gratis.
        /// </summary>
        public static string Probar3 {
            get {
                return ResourceManager.GetString("Probar3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string Productos {
            get {
                return ResourceManager.GetString("Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetir Contraseña.
        /// </summary>
        public static string RepetirContraseña {
            get {
                return ResourceManager.GetString("RepetirContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí, ya està registrada.
        /// </summary>
        public static string Respuesta1_1 {
            get {
                return ResourceManager.GetString("Respuesta1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, es un regisro nuevo de empresa.
        /// </summary>
        public static string Respuesta1_2 {
            get {
                return ResourceManager.GetString("Respuesta1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar  Imagen.
        /// </summary>
        public static string SeleccionarImagen {
            get {
                return ResourceManager.GetString("SeleccionarImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar  Tienda.
        /// </summary>
        public static string SeleccionarTienda {
            get {
                return ResourceManager.GetString("SeleccionarTienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sessión.
        /// </summary>
        public static string Sign_Out {
            get {
                return ResourceManager.GetString("Sign_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        public static string Siguiente {
            get {
                return ResourceManager.GetString("Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienda.
        /// </summary>
        public static string Tienda {
            get {
                return ResourceManager.GetString("Tienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiendas.
        /// </summary>
        public static string Tiendas {
            get {
                return ResourceManager.GetString("Tiendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad.
        /// </summary>
        public static string unidad {
            get {
                return ResourceManager.GetString("unidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa materiales.
        /// </summary>
        public static string Usa_materiales {
            get {
                return ResourceManager.GetString("Usa materiales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventas.
        /// </summary>
        public static string Ventas {
            get {
                return ResourceManager.GetString("Ventas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Ficha Material.
        /// </summary>
        public static string VerFichaMaterial {
            get {
                return ResourceManager.GetString("VerFichaMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Ficha Producto.
        /// </summary>
        public static string VerFichaProducto {
            get {
                return ResourceManager.GetString("VerFichaProducto", resourceCulture);
            }
        }
    }
}
